name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Build Project
        run: |
          echo "N" | pnpm compile -- ${{ github.ref_name }}

      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "DuckMod Add-On ${{ github.ref_name }}"
          body: "Please see CHANGELOG.md"
          generate_release_notes: false
          files: |
            releases/${{ github.ref_name }}/*
